/* Generated by PMersion canonical engines. Run scripts/lab/home-decision-snapshots.mjs. */
export const decisionBasis = {
  "version": "home-decision-alternatives-v1",
  "sourceAdapter": "apps/public-beta/src/lab-example.ts#publicSynthesisFromSelections",
  "sourceEngine": "packages/domain/experiments/project-reconciliation.ts",
  "generator": "scripts/lab/home-decision-snapshots.mjs",
  "scope": "Independent fictional alternatives, not cumulative and not saved visitor choices.",
  "fixedRisk": {
    "response": "accept_with_contingency",
    "day": 0,
    "qualified": false
  },
  "riskActionCostEUR": 0,
  "supplierDelayWorkingDays": 15,
  "dateBasis": "Abstract working days; no real calendar.",
  "reserveTreatment": "Contingency is already in the approved baseline, not an extra cost or a saving."
};
export const decisions = {
  "initial": {
    "plan": {
      "baseline": {
        "tasks": [
          {
            "id": "design",
            "start": 0,
            "finish": 10
          },
          {
            "id": "supplier",
            "start": 10,
            "finish": 30
          },
          {
            "id": "preparation",
            "start": 10,
            "finish": 25
          },
          {
            "id": "integration",
            "start": 30,
            "finish": 40
          },
          {
            "id": "acceptance",
            "start": 40,
            "finish": 45
          }
        ],
        "finishWorkingDay": 45
      },
      "forecast": {
        "tasks": [
          {
            "id": "design",
            "start": 0,
            "finish": 10
          },
          {
            "id": "supplier",
            "start": 10,
            "finish": 45
          },
          {
            "id": "preparation",
            "start": 10,
            "finish": 25
          },
          {
            "id": "integration",
            "start": 45,
            "finish": 55
          },
          {
            "id": "acceptance",
            "start": 55,
            "finish": 60
          }
        ],
        "finishWorkingDay": 60
      },
      "externalTargetWorkingDay": 47
    },
    "cost": 1090000,
    "finish": 60,
    "target": 47,
    "baseline": 1000000,
    "savings": 0,
    "actionCost": 0,
    "postponed": 0,
    "label": "Situation initiale",
    "lesson": "La prévision dépasse le budget approuvé de 90 000 €. La livraison est prévue 13 jours après la cible externe.",
    "caution": "Projet fictif. Les jours sont des jours de travail abstraits, sans calendrier réel.",
    "route": "/beta/#/atelier/budget"
  },
  "savings": {
    "plan": {
      "baseline": {
        "tasks": [
          {
            "id": "design",
            "start": 0,
            "finish": 10
          },
          {
            "id": "supplier",
            "start": 10,
            "finish": 30
          },
          {
            "id": "preparation",
            "start": 10,
            "finish": 25
          },
          {
            "id": "integration",
            "start": 30,
            "finish": 40
          },
          {
            "id": "acceptance",
            "start": 40,
            "finish": 45
          }
        ],
        "finishWorkingDay": 45
      },
      "forecast": {
        "tasks": [
          {
            "id": "design",
            "start": 0,
            "finish": 10
          },
          {
            "id": "supplier",
            "start": 10,
            "finish": 45
          },
          {
            "id": "preparation",
            "start": 10,
            "finish": 25
          },
          {
            "id": "integration",
            "start": 45,
            "finish": 55
          },
          {
            "id": "acceptance",
            "start": 55,
            "finish": 60
          }
        ],
        "finishWorkingDay": 60
      },
      "externalTargetWorkingDay": 47
    },
    "cost": 1050000,
    "finish": 60,
    "target": 47,
    "baseline": 1000000,
    "savings": 40000,
    "actionCost": 0,
    "postponed": 0,
    "label": "Économiser 40 000 €",
    "lesson": "Les économies vérifiées réduisent le coût final prévu à 1 050 000 €. Le retard reste de 13 jours.",
    "caution": "Les 40 000 € sont supposés vérifiés dans cet essai. Choisir une option ne prouve pas son exécution.",
    "route": "/beta/#/atelier/budget"
  },
  "defer": {
    "plan": {
      "baseline": {
        "tasks": [
          {
            "id": "design",
            "start": 0,
            "finish": 10
          },
          {
            "id": "supplier",
            "start": 10,
            "finish": 30
          },
          {
            "id": "preparation",
            "start": 10,
            "finish": 25
          },
          {
            "id": "integration",
            "start": 30,
            "finish": 40
          },
          {
            "id": "acceptance",
            "start": 40,
            "finish": 45
          }
        ],
        "finishWorkingDay": 45
      },
      "forecast": {
        "tasks": [
          {
            "id": "design",
            "start": 0,
            "finish": 10
          },
          {
            "id": "supplier",
            "start": 10,
            "finish": 45
          },
          {
            "id": "preparation",
            "start": 10,
            "finish": 25
          },
          {
            "id": "integration",
            "start": 45,
            "finish": 55
          },
          {
            "id": "acceptance",
            "start": 55,
            "finish": 60
          }
        ],
        "finishWorkingDay": 60
      },
      "externalTargetWorkingDay": 47
    },
    "cost": 1090000,
    "finish": 60,
    "target": 47,
    "baseline": 1000000,
    "savings": 0,
    "actionCost": 0,
    "postponed": 60000,
    "label": "Reporter 60 000 €",
    "lesson": "60 000 € de dépenses sont décalés, mais aucune économie n’est créée. Le coût final reste à 1 090 000 €.",
    "caution": "Le report n’annule pas la dépense. Aucun échéancier de paiement ni effet sur le délai n’est modélisé dans cet essai.",
    "route": "/beta/#/atelier/budget"
  },
  "recover": {
    "plan": {
      "baseline": {
        "tasks": [
          {
            "id": "design",
            "start": 0,
            "finish": 10
          },
          {
            "id": "supplier",
            "start": 10,
            "finish": 30
          },
          {
            "id": "preparation",
            "start": 10,
            "finish": 25
          },
          {
            "id": "integration",
            "start": 30,
            "finish": 40
          },
          {
            "id": "acceptance",
            "start": 40,
            "finish": 45
          }
        ],
        "finishWorkingDay": 45
      },
      "forecast": {
        "tasks": [
          {
            "id": "design",
            "start": 0,
            "finish": 10
          },
          {
            "id": "supplier",
            "start": 10,
            "finish": 45
          },
          {
            "id": "preparation",
            "start": 10,
            "finish": 25
          },
          {
            "id": "integration",
            "start": 45,
            "finish": 51
          },
          {
            "id": "acceptance",
            "start": 51,
            "finish": 56
          }
        ],
        "finishWorkingDay": 56
      },
      "externalTargetWorkingDay": 47
    },
    "cost": 1096000,
    "finish": 56,
    "target": 47,
    "baseline": 1000000,
    "savings": 0,
    "actionCost": 6000,
    "postponed": 0,
    "label": "Récupérer 4 jours",
    "lesson": "La fin prévue avance de J60 à J56 pour 6 000 € d’action. Il reste 9 jours de retard sur la cible J47.",
    "caution": "Les interfaces et le gain de quatre jours sont supposés vérifiés. Le coût de l’action est prévu, pas déclaré payé.",
    "route": "/beta/#/atelier/planning"
  }
};
