import { expect, test } from "@playwright/test";
test("homepage previews lead to the real workshops and remain keyboard operable", async ({page}, info) => {
  await page.goto("/");
  await expect(page.getByRole("heading",{level:1})).toContainText("La gestion de projet");
  await expect(page.locator(".galaxy,.big-planet,.space-layer")).toHaveCount(0);
  await page.getByRole("button",{name:/02 Planning/}).focus();
  await page.keyboard.press("Enter");
  await expect(page.locator("#metric-value")).toHaveText("J60");
  await expect(page.locator("#preview-link")).toHaveAttribute("href","/beta/#/atelier/planning");
  await page.getByRole("button",{name:/03 Risques/}).click();
  await expect(page.locator("#metric-value")).toHaveText("20 / 25");
  expect(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth+1)).toBe(true);
  await page.screenshot({path:info.outputPath("home-risk-preview.png")});
  await page.locator("#preview-link").click();
  await expect(page.getByRole("heading",{level:1})).toContainText("Un risque se pilote");
  await page.getByRole("link",{name:"Synthèse du comité",exact:true}).click();
  await page.getByRole("button",{name:"Exemple guidé",exact:true}).click();
  await expect(page.getByTestId("synthesis-cost")).toBeVisible();
});
test('homepage hypotheses share canonical calculations and reduced motion is respected', async ({page},info) => {
 await page.goto('/');
 await page.getByRole('button',{name:/Tester 40 000/}).click();
 await expect(page.locator('#metric-value')).toHaveText('1 050 000 €');
 await expect(page.locator('#metric-variance')).toHaveText('+5 %');
 await page.getByRole('button',{name:/02 Planning/}).click();
 await page.getByRole('button',{name:/Tester les conditions/}).click();
 await expect(page.locator('#metric-value')).toHaveText('J56');
 await page.getByRole('button',{name:/03 Risques/}).click();
 await page.getByRole('button',{name:/Tester une alternative/}).click();
 await expect(page.locator('#metric-value')).toHaveText('8 / 25');
 expect(await page.evaluate(()=>document.getAnimations().length)).toBe(0);
 await page.getByRole('button',{name:'Effets vérifiés',exact:true}).click();
 await expect(page.locator('#living-cost')).toHaveText('1 061 000 €');
 await expect(page.locator('#living-date')).toHaveText('J56');
 await expect(page.locator('#living-bar')).toHaveAttribute('width','252');
 await page.locator('#living-title').scrollIntoViewIfNeeded();
 await page.screenshot({path:info.outputPath('11-living-dossier.png')});
 await page.getByRole('button',{name:'Incident',exact:true}).click();
 await expect(page.locator('#living-cost')).toHaveText('À compléter');
 await expect(page.locator('#living-date')).toHaveText('À compléter');
 await expect(page.locator('#living-bar')).toHaveAttribute('visibility','hidden');
 await expect(page.locator('#living-insight')).toContainText('sous-total connu');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth+1)).toBe(true);
});
test('homepage retains readable facts without JavaScript and supports finite motion', async ({page,context},info) => {
 await page.emulateMedia({reducedMotion:'no-preference'});
 await page.goto('/');
 await page.getByRole('button',{name:/02 Planning/}).click();
 await expect(page.locator('#metric-value')).toHaveText('J60');
 await expect.poll(()=>page.evaluate(()=>document.getAnimations().filter(item=>item.effect.getTiming().iterations === Infinity).length)).toBe(0);
 await page.getByRole('heading',{level:1}).scrollIntoViewIfNeeded();
 await page.screenshot({path:info.outputPath('12-home.png'),animations:'disabled'});
 const staticPage = await context.newPage();
 await staticPage.route('**/*.js',route=>route.abort());
 await staticPage.goto('/');
 await expect(staticPage.getByRole('heading',{level:1})).toContainText('La gestion de projet');
 await expect(staticPage.locator('#living-cost')).toHaveText('1 101 000 €');
 await expect(staticPage.getByRole('link',{name:/Essayer la bêta PMersion/})).toHaveAttribute('href','/beta/');
});
